USE ComiditasYaDW;

INSERT INTO Dim_Ubicacion(departamento, provincia) VALUES
	('José C. Paz', 'Buenos Aires'),
    ('O Higgins', 'Chaco'),
    ('Trenel', 'La Pampa'),
    ('Adolfo Gonzales Chaves', 'Buenos Aires'),
    ('General Juan Madariaga', 'Buenos Aires'),
    ('Tandil', 'Buenos Aires'),
    ('Alberdi', 'Santiago del Estero'),
    ('Quemú Quemú', 'La Pampa'),
    ('Capital', 'La Pampa'),
    ('Rivadavia', 'Santiago del Estero'),
    ('Juan F. Ibarra', 'Santiago del Estero'),
    ('General Taboada', 'Santiago del Estero'),
    ('La Paz', 'Mendoza'),
    ('Coronel Pringles', 'Buenos Aires'),
    ('Tigre', 'Buenos Aires'),
    ('Catriló', 'La Pampa'),
    ('Atreucó', 'La Pampa'),
    ('Guatraché', 'La Pampa'),
    ('Utracán', 'La Pampa'),
    ('Loventué', 'La Pampa'),
    ('Hucal', 'La Pampa'),
    ('Chalileo', 'La Pampa'),
    ('Chical Co', 'La Pampa'),
    ('Esquina', 'Corrientes'),
    ('Sauce', 'Corrientes'),
    ('Curuzu Cuatia', 'Corrientes'),
    ('San Martín', 'Corrientes'),
    ('Rawson', 'Chubut'),
    ('Mercedes', 'Corrientes'),
    ('Paso de los Libres', 'Corrientes'),
    ('General Alvear', 'Corrientes'),
    ('Choya', 'Santiago del Estero'),
    ('Santa Rosa', 'Mendoza'),
    ('Rivadavia', 'Mendoza'),
    ('Tornquist', 'Buenos Aires'),
    ('Chamical', 'La Rioja'),
    ('Arauco', 'La Rioja'),
    ('Campana', 'Buenos Aires'),
    ('Santa Rosa', 'Catamarca'),
    ('La Paz', 'Catamarca'),
    ('Magallanes', 'Santa Cruz'),
    ('Corpen Aike', 'Santa Cruz'),
    ('Conesa', 'Río Negro'),
    ('Sargento Cabral', 'Chaco'),
    ('Independencia', 'Chaco'),
    ('Mayor Luis J. Fontana', 'Chaco'),
    ('Fray Justo Santa María de Oro', 'Chaco'),
    ('1° de Mayo', 'Chaco'),
    ('Ayacucho', 'San Luis'),
    ('Maipú', 'Buenos Aires'),
    ('12 de Octubre', 'Chaco'),
    ('Santa María', 'Córdoba'),
    ('San Alberto', 'Córdoba'),
    ('Río Segundo', 'Córdoba'),
    ('San Justo', 'Córdoba'),
    ('Unión', 'Córdoba'),
    ('Tercero Arriba', 'Córdoba'),
    ('Cerrillos', 'Salta'),
    ('Río Cuarto', 'Córdoba'),
    ('Tupungato', 'Mendoza'),
    ('Pilagás', 'Formosa'),
    ('Laishí', 'Formosa'),
    ('Pirané', 'Formosa'),
    ('General Güemes', 'Chaco'),
    ('Ñorquinco', 'Río Negro'),
    ('Adolfo Alsina', 'Buenos Aires'),
    ('Puán', 'Buenos Aires'),
    ('Villarino', 'Buenos Aires'),
    ('Presidente Roque Sáenz Peña', 'Córdoba'),
    ('General Villegas', 'Buenos Aires'),
    ('General Roca', 'Córdoba'),
    ('General Alvear', 'Mendoza'),
    ('Río Hondo', 'Santiago del Estero'),
    ('San Pedro', 'Buenos Aires'),
    ('Rivadavia', 'Salta'),
    ('Rosario de Lerma', 'Salta'),
    ('Ledesma', 'Jujuy'),
    ('Capital', 'Corrientes'),
    ('Capital', 'Misiones'),
    ('Iguazú', 'Misiones'),
    ('Oberá', 'Misiones'),
    ('San Ignacio', 'Misiones'),
    ('Capital', 'La Rioja'),
    ('Río Seco', 'Córdoba'),
    ('Avellaneda', 'Río Negro'),
    ('General Roca', 'Río Negro'),
    ('San Fernando', 'Chaco'),
    ('Belgrano', 'San Luis'),
    ('Los Lagos', 'Neuquén'),
    ('Belén', 'Catamarca'),
    ('Confluencia', 'Neuquén'),
    ('Picunches', 'Neuquén'),
    ('Añelo', 'Neuquén'),
    ('Loncopué', 'Neuquén'),
    ('Ñorquín', 'Neuquén'),
    ('Capital', 'Catamarca'),
    ('Ancasti', 'Catamarca'),
    ('Pehuenches', 'Neuquén'),
    ('Minas', 'Neuquén'),
    ('Chos Malal', 'Neuquén'),
    ('Cushamen', 'Chubut'),
    ('Lago Buenos Aires', 'Santa Cruz'),
    ('Comuna 2', 'Ciudad Autónoma de Buenos Aires'),
    ('Comuna 8', 'Ciudad Autónoma de Buenos Aires'),
    ('Ramón Lista', 'Formosa'),
    ('Sobremonte', 'Córdoba'),
    ('Banda', 'Santiago del Estero'),
    ('Chivilcoy', 'Buenos Aires'),
    ('Villa Constitución', 'Santa Fe'),
    ('Mártires', 'Chubut'),
    ('Sarmiento', 'Santiago del Estero'),
    ('Deseado', 'Santa Cruz'),
    ('Languiñeo', 'Chubut'),
    ('Belgrano', 'Santiago del Estero'),
    ('Aguirre', 'Santiago del Estero'),
    ('Comuna 14', 'Ciudad Autónoma de Buenos Aires'),
    ('Guasayán', 'Santiago del Estero'),
    ('Capital', 'Córdoba'),
    ('Antofagasta de la Sierra', 'Catamarca'),
    ('San Carlos', 'Mendoza'),
    ('Futaleufú', 'Chubut'),
    ('Río Chico', 'Santa Cruz'),
    ('Lago Argentino', 'Santa Cruz'),
    ('El Cuy', 'Río Negro'),
    ('Las Heras', 'Mendoza'),
    ('Lavalle', 'Mendoza'),
    ('Pichi Mahuida', 'Río Negro'),
    ('Adolfo Alsina', 'Río Negro'),
    ('Comuna 3', 'Ciudad Autónoma de Buenos Aires'),
    ('Capital', 'Santiago del Estero'),
    ('General Alvear', 'Buenos Aires'),
    ('Loreto', 'Santiago del Estero'),
    ('Villaguay', 'Entre Ríos'),
    ('Castelli', 'Buenos Aires'),
    ('San Salvador', 'Entre Ríos'),
    ('Almirante Brown', 'Buenos Aires'),
    ('Nogoyá', 'Entre Ríos'),
    ('Tala', 'Entre Ríos'),
    ('La Paz', 'Entre Ríos'),
    ('San Lorenzo', 'Chaco'),
    ('La Plata', 'Buenos Aires'),
    ('Brandsen', 'Buenos Aires'),
    ('25 de Mayo', 'Buenos Aires'),
    ('Pehuajó', 'Buenos Aires'),
    ('General Belgrano', 'Buenos Aires'),
    ('Capayán', 'Catamarca'),
    ('Monte', 'Buenos Aires'),
    ('Roque Pérez', 'Buenos Aires'),
    ('Pilar', 'Buenos Aires'),
    ('Luján', 'Buenos Aires'),
    ('Azul', 'Buenos Aires'),
    ('Concepción', 'Misiones'),
    ('Merlo', 'Buenos Aires'),
    ('Chacabuco', 'Buenos Aires'),
    ('Carmen de Areco', 'Buenos Aires'),
    ('General Rodríguez', 'Buenos Aires'),
    ('Exaltación de la Cruz', 'Buenos Aires'),
    ('San Miguel', 'Buenos Aires'),
    ('San Andrés de Giles', 'Buenos Aires'),
    ('Junín', 'Buenos Aires'),
    ('Marcos Paz', 'Buenos Aires'),
    ('Juárez Celman', 'Córdoba'),
    ('Lihuel Calel', 'La Pampa'),
    ('Mercedes', 'Buenos Aires'),
    ('2 de Abril', 'Chaco'),
    ('Hurlingham', 'Buenos Aires'),
    ('Morón', 'Buenos Aires'),
    ('Ciudad Libertador San Martín', 'Buenos Aires'),
    ('La Candelaria', 'Salta'),
    ('Ituzaingó', 'Buenos Aires'),
    ('La Capital', 'Santa Fe'),
    ('Santo Tomé', 'Corrientes'),
    ('Saladas', 'Corrientes'),
    ('General Paz', 'Corrientes'),
    ('Suipacha', 'Buenos Aires'),
    ('Tres de Febrero', 'Buenos Aires'),
    ('Coronel Felipe Varela', 'La Rioja'),
    ('Alberti', 'Buenos Aires'),
    ('Lanús', 'Buenos Aires'),
    ('General Las Heras', 'Buenos Aires'),
    ('Lomas de Zamora', 'Buenos Aires'),
    ('Navarro', 'Buenos Aires'),
    ('Cañuelas', 'Buenos Aires'),
    ('Guachipas', 'Salta'),
    ('Cafayate', 'Salta'),
    ('Lobos', 'Buenos Aires'),
    ('Quilmes', 'Buenos Aires'),
    ('Pila', 'Buenos Aires'),
    ('General La Madrid', 'Buenos Aires'),
    ('Bolívar', 'Buenos Aires'),
    ('Balcarce', 'Buenos Aires'),
    ('Hipólito Yrigoyen', 'Buenos Aires'),
    ('Dolores', 'Buenos Aires'),
    ('Tres Lomas', 'Buenos Aires'),
    ('Ayacucho', 'Buenos Aires'),
    ('Bella Vista', 'Corrientes'),
    ('Tapenagá', 'Chaco'),
    ('Concordia', 'Entre Ríos'),
    ('Federal', 'Entre Ríos'),
    ('Gualeguaychú', 'Entre Ríos'),
    ('Islas del Ibicuy', 'Entre Ríos'),
    ('General Pinto', 'Buenos Aires'),
    ('Guaminí', 'Buenos Aires'),
    ('Avellaneda', 'Buenos Aires'),
    ('Calingasta', 'San Juan'),
    ('25 de Mayo', 'San Juan'),
    ('Colón', 'Buenos Aires'),
    ('San Cayetano', 'Buenos Aires'),
    ('Tres Arroyos', 'Buenos Aires'),
    ('Figueroa', 'Santiago del Estero'),
    ('Saavedra', 'Buenos Aires'),
    ('Monte Hermoso', 'Buenos Aires'),
    ('Lobería', 'Buenos Aires'),
    ('Berisso', 'Buenos Aires'),
    ('Tordillo', 'Buenos Aires'),
    ('Ramallo', 'Buenos Aires'),
    ('San Nicolás', 'Buenos Aires'),
    ('Moreno', 'Santiago del Estero'),
    ('General Guido', 'Buenos Aires'),
    ('Chacabuco', 'Chaco'),
    ('Guaymallén', 'Mendoza'),
    ('Capital', 'Salta'),
    ('25 de Mayo', 'Chaco'),
    ('Coronel Suárez', 'Buenos Aires'),
    ('Coronel Dorrego', 'Buenos Aires'),
    ('Necochea', 'Buenos Aires'),
    ('Independencia', 'La Rioja'),
    ('Maipú', 'Mendoza'),
    ('Capital', 'Mendoza'),
    ('Godoy Cruz', 'Mendoza'),
    ('Andalgalá', 'Catamarca'),
    ('Ambato', 'Catamarca'),
    ('Bahía Blanca', 'Buenos Aires'),
    ('General Alvarado', 'Buenos Aires'),
    ('General Pueyrredón', 'Buenos Aires'),
    ('Mar Chiquita', 'Buenos Aires'),
    ('Villa Gesell', 'Buenos Aires'),
    ('Junín', 'Mendoza'),
    ('Castro Barros', 'La Rioja'),
    ('Quitilipi', 'Chaco'),
    ('Pinamar', 'Buenos Aires'),
    ('General Lavalle', 'Buenos Aires'),
    ('La Costa', 'Buenos Aires'),
    ('Magdalena', 'Buenos Aires'),
    ('Sanagasta', 'La Rioja'),
    ('Vicente López', 'Buenos Aires'),
    ('Chilecito', 'La Rioja'),
    ('Presidencia de la Plaza', 'Chaco'),
    ('Victoria', 'Entre Ríos'),
    ('General Ángel V. Peñaloza', 'La Rioja'),
    ('Diamante', 'Entre Ríos'),
    ('Uruguay', 'Entre Ríos'),
    ('Paraná', 'Entre Ríos'),
    ('Saladillo', 'Buenos Aires'),
    ('Las Flores', 'Buenos Aires'),
    ('Rojas', 'Buenos Aires'),
    ('Escobar', 'Buenos Aires'),
    ('Pergamino', 'Buenos Aires'),
    ('General Juan F. Quiroga', 'La Rioja'),
    ('Lules', 'Tucumán'),
    ('Yerba Buena', 'Tucumán'),
    ('Tafí Viejo', 'Tucumán'),
    ('Burruyacú', 'Tucumán'),
    ('Rosario Vera Peñaloza', 'La Rioja'),
    ('Vera', 'Santa Fe'),
    ('9 de Julio', 'Santa Fe'),
    ('Iglesia', 'San Juan'),
    ('Valle Fértil', 'San Juan'),
    ('Ullum', 'San Juan'),
    ('Albardón', 'San Juan'),
    ('Zonda', 'San Juan'),
    ('Gobernador Dupuy', 'San Luis'),
    ('Cachi', 'Salta'),
    ('Chicoana', 'Salta'),
    ('La Viña', 'Salta'),
    ('Rauch', 'Buenos Aires'),
    ('Metán', 'Salta'),
    ('Molinos', 'Salta'),
    ('Salliqueló', 'Buenos Aires'),
    ('Berazategui', 'Buenos Aires'),
    ('General Güemes', 'Salta'),
    ('San Carlos', 'Salta'),
    ('Rancul', 'La Pampa'),
    ('Conhelo', 'La Pampa'),
    ('Fray Mamerto Esquiú', 'Catamarca'),
    ('General Ocampo', 'La Rioja'),
    ('Presidente Perón', 'Buenos Aires'),
    ('9 de julio', 'Río Negro'),
    ('General San Martín', 'La Rioja'),
    ('Atamisqui', 'Santiago del Estero'),
    ('Coronel de Marina Leonardo Rosales', 'Buenos Aires'),
    ('Famatina', 'La Rioja'),
    ('Libertad', 'Chaco'),
    ('Tolhuin', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    ('San Blas de Los Sauces', 'La Rioja'),
    ('Garay', 'Santa Fe'),
    ('Las Colonias', 'Santa Fe'),
    ('Realicó', 'La Pampa'),
    ('Formosa', 'Formosa'),
    ('Paclín', 'Catamarca'),
    ('El Alto', 'Catamarca'),
    ('Comandante Fernández', 'Chaco'),
    ('Leandro N. Alem', 'Buenos Aires'),
    ('General Belgrano', 'Chaco'),
    ('General Donovan', 'Chaco'),
    ('Tehuelches', 'Chubut'),
    ('Escalante', 'Chubut'),
    ('Ischilín', 'Córdoba'),
    ('Totoral', 'Córdoba'),
    ('General San Martín', 'Córdoba'),
    ('San Javier', 'Córdoba'),
    ('General Arenales', 'Buenos Aires'),
    ('Rivadavia', 'Buenos Aires'),
    ('Comuna 9', 'Ciudad Autónoma de Buenos Aires'),
    ('Angaco', 'San Juan'),
    ('Caucete', 'San Juan'),
    ('Picún Leufú', 'Neuquén'),
    ('Aluminé', 'Neuquén'),
    ('Sarmiento', 'Chubut'),
    ('General Paz', 'Buenos Aires'),
    ('San Miguel', 'Corrientes'),
    ('Comuna 7', 'Ciudad Autónoma de Buenos Aires'),
    ('25 de Mayo', 'Río Negro'),
    ('Comuna 10', 'Ciudad Autónoma de Buenos Aires'),
    ('Antártida Argentina', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    ('Islas del Atlántico Sur', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    ('Telsen', 'Chubut'),
    ('Comuna 11', 'Ciudad Autónoma de Buenos Aires'),
    ('San Antonio de Areco', 'Buenos Aires'),
    ('Moreno', 'Buenos Aires'),
    ('La Matanza', 'Buenos Aires'),
    ('Pilcaniyeu', 'Río Negro'),
    ('Ojo de Agua', 'Santiago del Estero'),
    ('Lezama', 'Buenos Aires'),
    ('Punta Indio', 'Buenos Aires'),
    ('El Carmen', 'Jujuy'),
    ('Santa María', 'Catamarca'),
    ('Gaiman', 'Chubut'),
    ('General Lamadrid', 'La Rioja'),
    ('Pocho', 'Córdoba'),
    ('Goya', 'Corrientes'),
    ('Lavalle', 'Corrientes'),
    ('San Roque', 'Corrientes'),
    ('Comuna 6', 'Ciudad Autónoma de Buenos Aires'),
    ('Tulumba', 'Córdoba'),
    ('Cruz del Eje', 'Córdoba'),
    ('Punilla', 'Córdoba'),
    ('Minas', 'Córdoba'),
    ('Valcheta', 'Río Negro'),
    ('San Antonio', 'Río Negro'),
    ('Pellegrini', 'Buenos Aires'),
    ('9 de Julio', 'Chaco'),
    ('La Caldera', 'Salta'),
    ('San Rafael', 'Mendoza'),
    ('Anta', 'Salta'),
    ('General Belgrano', 'La Rioja'),
    ('Copo', 'Santiago del Estero'),
    ('Vinchina', 'La Rioja'),
    ('Lácar', 'Neuquén'),
    ('Comuna 13', 'Ciudad Autónoma de Buenos Aires'),
    ('Güer Aike', 'Santa Cruz'),
    ('Río Grande', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    ('Ushuaia', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    ('Malargüe', 'Mendoza'),
    ('Pomán', 'Catamarca'),
    ('Graneros', 'Tucumán'),
    ('Rosario de la Frontera', 'Salta'),
    ('Paso de Indios', 'Chubut'),
    ('Almirante Brown', 'Chaco'),
    ('Valle Viejo', 'Catamarca'),
    ('Maipú', 'Chaco'),
    ('Robles', 'Santiago del Estero'),
    ('Colón', 'Entre Ríos'),
    ('Tunuyán', 'Mendoza'),
    ('Luján de Cuyo', 'Mendoza'),
    ('Río Senguer', 'Chubut'),
    ('Bariloche', 'Río Negro'),
    ('Huiliches', 'Neuquén'),
    ('Catán Lil', 'Neuquén'),
    ('Collón Curá', 'Neuquén'),
    ('Carlos Tejedor', 'Buenos Aires'),
    ('Arrecifes', 'Buenos Aires'),
    ('Capitán Sarmiento', 'Buenos Aires'),
    ('Salto', 'Buenos Aires'),
    ('Gualeguay', 'Entre Ríos'),
    ('Federación', 'Entre Ríos'),
    ('Feliciano', 'Entre Ríos'),
    ('9 de Julio', 'Buenos Aires'),
    ('Trenque Lauquen', 'Buenos Aires'),
    ('Carlos Casares', 'Buenos Aires'),
    ('Olavarría', 'Buenos Aires'),
    ('Esteban Echeverría', 'Buenos Aires'),
    ('General Viamonte', 'Buenos Aires'),
    ('Malvinas Argentinas', 'Buenos Aires'),
    ('Lincoln', 'Buenos Aires'),
    ('Tapalqué', 'Buenos Aires'),
    ('Toay', 'La Pampa'),
    ('Monte Caseros', 'Corrientes'),
    ('Bragado', 'Buenos Aires'),
    ('José M. Ezeiza', 'Buenos Aires'),
    ('Curacó', 'La Pampa'),
    ('Limay Mahuida', 'La Pampa'),
    ('Puelén', 'La Pampa'),
    ('Florencio Varela', 'Buenos Aires'),
    ('Silípica', 'Santiago del Estero'),
    ('25 de Mayo', 'Misiones'),
    ('San Vicente', 'Buenos Aires'),
    ('Daireaux', 'Buenos Aires'),
    ('9 de Julio', 'San Juan'),
    ('Rawson', 'San Juan'),
    ('Ensenada', 'Buenos Aires'),
    ('Laprida', 'Buenos Aires'),
    ('San Isidro', 'Buenos Aires'),
    ('Benito Juárez', 'Buenos Aires'),
    ('San Antonio', 'Jujuy'),
    ('Libertador General San Martín', 'Chaco'),
    ('Gastre', 'Chubut'),
    ('San Fernando', 'Buenos Aires'),
    ('Zárate', 'Buenos Aires'),
    ('Salavina', 'Santiago del Estero'),
    ('Pellegrini', 'Santiago del Estero'),
    ('Avellaneda', 'Santiago del Estero'),
    ('Bermejo', 'Chaco'),
    ('Junín', 'San Luis'),
    ('San Martín', 'Mendoza'),
    ('Zapala', 'Neuquén'),
    ('Colón', 'Córdoba'),
    ('Caseros', 'Santa Fe'),
    ('Rosario', 'Santa Fe'),
    ('San Lorenzo', 'Santa Fe'),
    ('Iriondo', 'Santa Fe'),
    ('Belgrano', 'Santa Fe'),
    ('San Jerónimo', 'Santa Fe'),
    ('Mitre', 'Santiago del Estero'),
    ('Santa Victoria', 'Salta'),
    ('General José de San Martín', 'Salta'),
    ('Pilcomayo', 'Formosa'),
    ('Río Primero', 'Córdoba'),
    ('Tinogasta', 'Catamarca'),
    ('Marcos Juárez', 'Córdoba'),
    ('Calamuchita', 'Córdoba'),
    ('Chacabuco', 'San Luis'),
    ('Juan Martín de Pueyrredón', 'San Luis'),
    ('General Pedernera', 'San Luis'),
    ('Patagones', 'Buenos Aires'),
    ('Libertador General San Martín', 'San Luis'),
    ('Coronel Pringles', 'San Luis'),
    ('Comuna 1', 'Ciudad Autónoma de Buenos Aires'),
    ('Comuna 4', 'Ciudad Autónoma de Buenos Aires'),
    ('Comuna 5', 'Ciudad Autónoma de Buenos Aires'),
    ('Caleu Caleu', 'La Pampa'),
    ('Jáchal', 'San Juan'),
    ('Quebrachos', 'Santiago del Estero'),
    ('Mburucuyá', 'Corrientes'),
    ('Empedrado', 'Corrientes'),
    ('Ituzaingó', 'Corrientes'),
    ('San Cosme', 'Corrientes'),
    ('Itatí', 'Corrientes'),
    ('Comuna 12', 'Ciudad Autónoma de Buenos Aires'),
    ('San Javier', 'Misiones'),
    ('Apóstoles', 'Misiones'),
    ('Eldorado', 'Misiones'),
    ('San Pedro', 'Misiones'),
    ('Montecarlo', 'Misiones'),
    ('Chascomús', 'Buenos Aires'),
    ('Comuna 15', 'Ciudad Autónoma de Buenos Aires'),
    ('San Martín', 'Santiago del Estero'),
    ('Jiménez', 'Santiago del Estero'),
    ('Baradero', 'Buenos Aires'),
    ('Humahuaca', 'Jujuy'),
    ('Yaví', 'Jujuy'),
    ('Santa Catalina', 'Jujuy'),
    ('San Pedro', 'Jujuy'),
    ('Valle Grande', 'Jujuy'),
    ('Patiño', 'Formosa'),
    ('Bermejo', 'Formosa'),
    ('Susques', 'Jujuy'),
    ('Iruya', 'Salta'),
    ('Matacos', 'Formosa'),
    ('Los Andes', 'Salta'),
    ('Orán', 'Salta'),
    ('Tilcara', 'Jujuy'),
    ('Palpalá', 'Jujuy'),
    ('Cochinoca', 'Jujuy'),
    ('Tumbaya', 'Jujuy'),
    ('Dr. Manuel Belgrano', 'Jujuy'),
    ('Santa Bárbara', 'Jujuy'),
    ('Rinconada', 'Jujuy'),
    ('La Poma', 'Salta'),
    ('Chicligasta', 'Tucumán'),
    ('Monteros', 'Tucumán'),
    ('Leales', 'Tucumán'),
    ('Famaillá', 'Tucumán'),
    ('Capital', 'Tucumán'),
    ('Cruz Alta', 'Tucumán'),
    ('Trancas', 'Tucumán'),
    ('Tafí del Valle', 'Tucumán'),
    ('San Martín', 'Santa Fe'),
    ('San Luis del Palmar', 'Corrientes'),
    ('Berón de Astrada', 'Corrientes'),
    ('Castellanos', 'Santa Fe'),
    ('San Justo', 'Santa Fe'),
    ('San Cristóbal', 'Santa Fe'),
    ('San Javier', 'Santa Fe'),
    ('General Obligado', 'Santa Fe'),
    ('Chimbas', 'San Juan'),
    ('San Martín', 'San Juan'),
    ('Biedma', 'Chubut'),
    ('Florentino Ameghino', 'Buenos Aires'),
    ('Florentino Ameghino', 'Chubut'),
    ('La Cocha', 'Tucumán'),
    ('Juan Bautista Alberdi', 'Tucumán'),
    ('Río Chico', 'Tucumán'),
    ('Simoca', 'Tucumán'),
    ('General López', 'Santa Fe'),
    ('Candelaria', 'Misiones'),
    ('Cainguás', 'Misiones'),
    ('Libertador General San Martín', 'Misiones'),
    ('General Manuel Belgrano', 'Misiones'),
    ('Guaraní', 'Misiones'),
    ('Rivadavia', 'San Juan'),
    ('Santa Lucía', 'San Juan'),
    ('Pocito', 'San Juan'),
    ('Sarmiento', 'San Juan'),
    ('Capital', 'San Juan'),
    ('Chapaleufú', 'La Pampa'),
    ('Maracó', 'La Pampa'),
    ('Concepción', 'Corrientes'),
    ('Leandro N. Alem', 'Misiones')
;
