import random


lista = """('lunch', 'pasta', 'pizza', 'Margarita', 250.0),
	('lunch', 'carne', 'milanesa', 'Clasica', 200.0),
	('lunch', 'carne', 'milanesa', 'Napolitana', 350.0),
	('lunch', 'carne', 'pollo', 'A la parrila', 350.0),
	('lunch', 'carne', 'pollo', 'spiedo', 400.0),
	('lunch', 'pasta', 'fideos', 'Bolognesa', 200.0),
	('lunch', 'pasta', 'fideos', 'Salsa Blanca', 150.0),
	('lunch', 'pasta', 'fideos', 'Pesto', 150.0),
	('lunch', 'pasta', 'ravioles', 'Bolognesa', 250.0),
	('lunch', 'pasta', 'ravioles', 'Salsa Blanca', 210.0),
	('dessert', 'helado', 'crema', 'Chocolate', 50.0),
	('dessert', 'helado', 'crema', 'Chocolate Almendrado', 50.0),
	('dessert', 'helado', 'crema', 'Dulce de Leche', 50.0),
	('dessert', 'helado', 'crema', 'Banana Split', 50.0),
	('dessert', 'helado', 'agua', 'Limon', 25.0),
	('dessert', 'helado', 'agua', 'Frutilla', 25.0),
	('dessert', 'helado', 'agua', 'Maracuya', 25.0),
	('dessert', 'helado', 'crema', 'Tramontana', 50.0),
	('dessert', 'helado', 'crema', 'Frutos del bosque', 50.0),
	('dessert', 'helado', 'crema', 'Quinotos', 50.0),
	('dinner', 'sandwich', 'lomo', 'Clasico', 450.0),
	('dinner', 'sandwich', 'lomo', 'Completo', 500.0),
	('dinner', 'sandwich', 'lomo', 'Lomo Pizza', 1000.0),
	('dinner', 'carne', 'asado', 'Parrillada', 2000.0),
	('dinner', 'carne', 'asado', 'Choripan', 100.0),
	('dinner', 'sopa', 'crema', 'Sopa de Calabaza', 200.0),
	('dinner', 'sopa', 'crema', 'Sopa de Espinaca', 200.0),
	('dinner', 'sopa', 'caldo', 'Sopa de Verduras', 200.0),
	('dinner', 'verdura', 'papa frita', 'Salchipapa', 1499.99),
	('dinner', 'pasta', 'ramen', 'Miso Ramen', 750.0),
	('dinner','caliente','quinoa','con pollo',310),
	('dinner','caliente','quinoa','con leche',330),
	('dinner','caliente','quinoa','con verduras',318),
	('dinner','caliente','quinoa','salteado',316),
	('dinner','caliente','quinoa','YULI',329),
	('dinner','caliente','quinoa','con mariscos',218),
	('dinner','caliente','quinoa','a lo cubano',359),
	('dinner','caliente','quinoa','peruano',330),
	('dinner','caliente','quinoa','primavera',356),
	('dinner','caliente','quinoa','con alboldigas',301),
	('dinner','caliente','quinoa','Ortiga',314),
	('dinner','caliente','quinoa','graneado',279),
	('dinner','caliente','quinoa','con chorizo',209),
	('dinner','caliente','quinoa','con Tofu',207),
	('dinner','caliente','quinoa','frito',215),
	('dinner','caliente','quinoa','Chino',354),
	('dinner','caliente','quinoa','integral',370),
	('dinner','caliente','quinoa','al curry',346),
	('dinner','caliente','quinoa','a la valenciana',326),
	('dinner','caliente','quinoa','con crema',277),
	('dinner','caliente','quinoa','bolognesa',340),
	('dinner','caliente','quinoa','con curcuma',318),
	('dinner','caliente','quinoa','con verdes',215),
	('dinner','caliente','quinoa','yamani con zapallo',215),
	('dinner','caliente','quinoa','con cerdo',256),
	('dinner','caliente','quinoa','con queso',364),
	('dinner','caliente','quinoa','tipo Thai',333),
	('dinner','caliente','quinoa','con atun',303),
	('dinner','caliente','quinoa','con salchicha',354),
	('dinner','caliente','quinoa','con especias americanas',281),
	('lunch','caliente','arroz','con pollo',224),
	('lunch','caliente','arroz','con leche',391),
	('lunch','caliente','arroz','con verduras',280),
	('lunch','caliente','arroz','salteado',288),
	('lunch','caliente','arroz','YULI',259),
	('lunch','caliente','arroz','con mariscos',265),
	('lunch','caliente','arroz','a lo cubano',324),
	('lunch','caliente','arroz','peruano',386),
	('lunch','caliente','arroz','primavera',201),
	('lunch','caliente','arroz','con alboldigas',363),
	('lunch','caliente','arroz','Ortiga',291),
	('lunch','caliente','arroz','graneado',360),
	('lunch','caliente','arroz','con chorizo',321),
	('lunch','caliente','arroz','con Tofu',223),
	('lunch','caliente','arroz','frito',371),
	('lunch','caliente','arroz','Chino',204),
	('lunch','caliente','arroz','integral',290),
	('lunch','caliente','arroz','al curry',341),
	('lunch','caliente','arroz','a la valenciana',279),
	('lunch','caliente','arroz','con crema',343),
	('lunch','caliente','arroz','bolognesa',289),
	('lunch','caliente','arroz','con curcuma',221),
	('lunch','caliente','arroz','con verdes',281),
	('lunch','caliente','arroz','yamani con zapallo',304),
	('lunch','caliente','arroz','con cerdo',372),
	('lunch','caliente','arroz','con queso',278),
	('lunch','caliente','arroz','tipo Thai',397),
	('lunch','caliente','arroz','con atun',397),
	('lunch','caliente','arroz','con salchicha',262),
	('lunch','caliente','arroz','con especias americanas',236),
	('lunch','caliente','paella','con pollo',355),
	('lunch','caliente','paella','con leche',211),
	('lunch','caliente','paella','con verduras',389),
	('lunch','caliente','paella','salteado',331),
	('lunch','caliente','paella','YULI',234),
	('lunch','caliente','paella','con mariscos',244),
	('lunch','caliente','paella','a lo cubano',218),
	('lunch','caliente','paella','peruano',316),
	('lunch','caliente','paella','primavera',360),
	('lunch','caliente','paella','con alboldigas',272),
	('lunch','caliente','paella','Ortiga',254),
	('lunch','caliente','paella','graneado',307),
	('lunch','caliente','paella','con chorizo',208),
	('lunch','caliente','paella','con Tofu',281),
	('lunch','caliente','paella','frito',334),
	('lunch','caliente','paella','Chino',285),
	('lunch','caliente','paella','integral',225),
	('lunch','caliente','paella','al curry',299),
	('lunch','caliente','paella','a la valenciana',204),
	('lunch','caliente','paella','con crema',260),
	('lunch','caliente','paella','bolognesa',201),
	('lunch','caliente','paella','con curcuma',272),
	('lunch','caliente','paella','con verdes',219),
	('lunch','caliente','paella','yamani con zapallo',258),
	('lunch','caliente','paella','con cerdo',400),
	('lunch','caliente','paella','con queso',279),
	('lunch','caliente','paella','tipo Thai',370),
	('lunch','caliente','paella','con atun',335),
	('lunch','caliente','paella','con salchicha',351),
	('lunch','caliente','paella','con especias americanas',210),
	('dinner','caliente','lentejas','con pollo',372),
	('dinner','caliente','lentejas','con leche',312),
	('dinner','caliente','lentejas','con verduras',229),
	('dinner','caliente','lentejas','salteado',383),
	('dinner','caliente','lentejas','YULI',334),
	('dinner','caliente','lentejas','con mariscos',245),
	('dinner','caliente','lentejas','a lo cubano',255),
	('dinner','caliente','lentejas','peruano',269),
	('dinner','caliente','lentejas','primavera',327),
	('dinner','caliente','lentejas','con alboldigas',372),
	('dinner','caliente','lentejas','Ortiga',371),
	('dinner','caliente','lentejas','graneado',265),
	('dinner','caliente','lentejas','con chorizo',323),
	('dinner','caliente','lentejas','con Tofu',242),
	('dinner','caliente','lentejas','frito',211),
	('dinner','caliente','lentejas','Chino',207),
	('dinner','caliente','lentejas','integral',278),
	('dinner','caliente','lentejas','al curry',369),
	('dinner','caliente','lentejas','a la valenciana',285),
	('dinner','caliente','lentejas','con crema',345),
	('dinner','caliente','lentejas','bolognesa',215),
	('dinner','caliente','lentejas','con curcuma',233),
	('dinner','caliente','lentejas','con verdes',203),
	('dinner','caliente','lentejas','yamani con zapallo',349),
	('dinner','caliente','lentejas','con cerdo',280),
	('dinner','caliente','lentejas','con queso',322),
	('dinner','caliente','lentejas','tipo Thai',291),
	('dinner','caliente','lentejas','con atun',261),
	('dinner','caliente','lentejas','con salchicha',251),
	('dinner','caliente','lentejas','con especias americanas',344),
	('lunch','caliente','pescado','corvina',443),
	('lunch','caliente','pescado','carpa',496),
	('lunch','caliente','pescado','salmon',449),
	('lunch','caliente','pescado','dorado',513),
	('lunch','caliente','pescado','frito',590),
	('lunch','caliente','pescado','filete de merluza',408),
	('lunch','caliente','pescado','empanado',436),
	('lunch','caliente','pescado','con pesto',524),
	('lunch','caliente','pescado','con nueces',498),
	('lunch','caliente','pescado','al chupin',524),
	('lunch','caliente','pescado','al limon',467),
	('lunch','caliente','pescado','al horno',558),
	('lunch','caliente','pescado','a la parrilla',513),
	('lunch','caliente','pescado','con verduras salteadas al wok',578),
	('lunch','caliente','pescado','al pomelo',503),
	('lunch','caliente','pescado','con papas y crema',454),
	('lunch','caliente','pescado','con brocloi y tapenade',565),
	('lunch','caliente','pescado','al escabeche',566),
	('lunch','caliente','pescado','al vapor',477),
	('lunch','caliente','pescado','al tomate',438),
	('lunch','caliente','pescado','al ajo',489),
	('lunch','caliente','pescado','al cilantro',484),
	('lunch','caliente','pescado','al curry',524),
	('lunch','caliente','pescado','rebozado',542),
	('lunch','caliente','pescado','a la napolitana',498),
	('lunch','caliente','pescado','a la crema',491),
	('lunch','caliente','pescado','con papas',453),
	('lunch','sandwich','vegetariano','verduras salteadas',241),
	('lunch','sandwich','vegetariano','mix verdes',233),
	('lunch','sandwich','vegetariano','capresse',260),
	('lunch','sandwich','vegetariano','cuatro quesos',279),
	('lunch','sandwich','vegetariano','de palta y queso',268),
	('lunch','sandwich','vegetariano','a la provenzal',239),
	('lunch','sandwich','vegetariano','pan de avena',294),
	('lunch','sandwich','vegetariano','con palmitos',273),
	('lunch','sandwich','vegetariano','de anana',244),
	('lunch','sandwich','vegetariano','de huevo',207),
	('lunch','sandwich','vegetariano','de zanahoria',258),
	('lunch','sandwich','vegetariano','arvejas',299),
	('lunch','sandwich','miga','pollo',153),
	('lunch','sandwich','miga','bondiola',208),
	('lunch','sandwich','miga','peceto',288),
	('lunch','sandwich','miga','jamon y queso',220),
	('lunch','sandwich','miga','cuatro quesos',238),
	('lunch','sandwich','miga','philadelfia',208),
	('lunch','sandwich','miga','mortadela',274),
	('lunch','sandwich','miga','cuatro quesos',167),
	('lunch','sandwich','miga','alboldiga',277),
	('lunch','sandwich','miga','tostado',243),
	('lunch','sandwich','miga','de cerdo',240),
	('lunch','sandwich','miga','de milanesa',271),
	('lunch','sandwich','miga','BLT',260),
	('lunch','sandwich','miga','pollo adobado',200),
	('lunch','sandwich','miga','de campo',187),
	('lunch','sandwich','miga','de vacio',255),
	('lunch','sandwich','miga','de atun',208),
	('lunch','sandwich','miga','barbacoa',186),
	('dessert', 'trufas', 'dulce', 'cava y frambuesa', 251),
	('dessert', 'trufas', 'dulce', 'chocolate', 251),
	('dessert', 'trufas', 'dulce', 'dulce de leche', 251),
	('dessert', 'tarta', 'pie', 'limon', 525),
	('dessert', 'tarta', 'pie', 'queso', 525),
	('dessert', 'tarta', 'pie', 'frutos del bosque', 525),
	('dessert', 'tarta', 'biscocho', 'manzana', 525),
	('dessert', 'tarta', 'biscocho', 'vainilla', 250)"""
# 44999 tiempos
# 2481 resta
# 528 ubic
# 29 comid
# import com
# import envio
# tot
# (1, 7, 1, 1, 500, 30, 530)
lista = lista.split("\n")
lista1 = []
for i in lista:
    item = i.split(",")
    for j in item:
        if ")" in j:
            lista1.append(float(j.strip(")")))
file = open('./text.txt', 'a')
for i in range(5000):
    tiempo = str(random.choice([8865, 17865, 26865, 35865, 44865]))# str(random.randint(36001, 45000))  # 1 - 45000
    resta = str(random.randint(1, 2482))  # 1 - 2482
    ubic = str(random.randint(1, 529))  # 1 - 529
    comid = random.randint(0, len(lista1)-1) # 0 - len(lista1)-1
    env = random.randint(25, 100)
    file.write("\t(" + tiempo + ", " + resta + ", " + ubic + ", " + str(comid+1) + ", " + str(lista1[comid]) + ", " + str(env) + ", " + str(lista1[comid] + env) + "),\n")
# primero 5000 pedidos 2016 del 1 al 9000 DONE
# primero 7000 pedidos 2017 del 9001 al 18000 DONE
# primero 10000 pedidos 2018 del 18001 al 27000 DONE
# primero 12300 pedidos 2019 del 27001 al 36000 DONE
# primero 18682 pedidos 2020 del 36001 al 45000 DONE
"""
) AS tabla(id_tiempo, id_restaurante, id_ubicacion, id_comida, importe_comida, importe_envio, importe_total);

USE ComiditasYaDW;

INSERT INTO Fact_Pedido (id_tiempo, id_restaurante, id_ubicacion, id_comida, importe_comida, importe_envio, importe_total) SELECT id_tiempo, id_restaurante, id_ubicacion, id_comida, importe_comida, importe_envio, importe_total FROM (VALUES
"""
