/*Lista de scripts para crear la BD escuela en MySQL
RECORDAR hay que copiar y pegar sentencia por sentencia en el BrowserSQL, sino no parsea el punto y coma*/

CREATE TABLE LOCALIDADES(IDLOCALIDAD INT NOT NULL, NOM_LOCALIDAD VARCHAR(45) NOT NULL, COD_POST SMALLINT NOT NULL,
CONSTRAINT PK_LOCALIDAD PRIMARY KEY(IDLOCALIDAD));

CREATE TABLE ALUMNOS(DNI INT NOT NULL, APELLIDO VARCHAR(40) NOT NULL, NOMBRE VARCHAR(40) NOT NULL, FECHA_NAC DATE NOT NULL,
DIRECCION VARCHAR(70) NOT NULL, IDLOCALIDAD INT NOT NULL,
CONSTRAINT PK_ALUMNO PRIMARY KEY(DNI),
CONSTRAINT FK_LOCALIDAD FOREIGN KEY(IDLOCALIDAD) REFERENCES LOCALIDADES(IDLOCALIDAD));

ALTER TABLE ALUMNOS ADD COLUMN EMAIL VARCHAR(35) NOT NULL, ADD COLUMN TELEFONO VARCHAR(12) NOT NULL;

CREATE TABLE MATERIAS (IDMATERIA INT NOT NULL, NOM_MATERIA VARCHAR(40) NOT NULL,
CONSTRAINT PK_MATERIA PRIMARY KEY(IDMATERIA));

CREATE TABLE NOTAS (IDMATERIA INT NOT NULL, DNI INT NOT NULL, PARCIAL_1 DECIMAL(4,2), PARCIAL_2 DECIMAL(4,2),
CONSTRAINT PK_NOTAS PRIMARY KEY(IDMATERIA,DNI),
CONSTRAINT FK_ALUMNOS FOREIGN KEY(DNI) REFERENCES ALUMNOS(DNI),
CONSTRAINT FK_MATERIAS FOREIGN KEY(IDMATERIA) REFERENCES MATERIAS(IDMATERIA));

ALTER TABLE NOTAS ADD COLUMN APROBADO TINYINT NOT NULL DEFAULT FALSE; 

CREATE TABLE Notas (IdMateria INT NOT NULL, DNI INT NOT NULL, Parcial_1 DECIMAL(4,2), Parcial_2 DECIMAL(4,2),
CONSTRAINT PK_Notas PRIMARY KEY(IdMateria,DNI),
CONSTRAINT FK_Alumnos FOREIGN KEY(DNI) REFERENCES Alumnos(DNI),
CONSTRAINT FK_Materias FOREIGN KEY(IdMateria) REFERENCES Materias(IdMateria));
