USE ComiditasYaDW;

INSERT INTO Dim_Comida (clasificacion, categoria, tipo_comida, nombre, precio) VALUES
	('lunch', 'pasta', 'pizza', 'Margarita', 250.0),
	('lunch', 'carne', 'milanesa', 'Clasica', 200.0),
	('lunch', 'carne', 'milanesa', 'Napolitana', 350.0),
	('lunch', 'carne', 'pollo', 'A la parrila', 350.0),
	('lunch', 'carne', 'pollo', 'spiedo', 400.0),
	('lunch', 'pasta', 'fideos', 'Bolognesa', 200.0),
	('lunch', 'pasta', 'fideos', 'Salsa Blanca', 150.0),
	('lunch', 'pasta', 'fideos', 'Pesto', 150.0),
	('lunch', 'pasta', 'ravioles', 'Bolognesa', 250.0),
	('lunch', 'pasta', 'ravioles', 'Salsa Blanca', 210.0),
	('dessert', 'helado', 'crema', 'Chocolate', 50.0),
	('dessert', 'helado', 'crema', 'Chocolate Almendrado', 50.0),
	('dessert', 'helado', 'crema', 'Dulce de Leche', 50.0),
	('dessert', 'helado', 'crema', 'Banana Split', 50.0),
	('dessert', 'helado', 'agua', 'Limon', 25.0),
	('dessert', 'helado', 'agua', 'Frutilla', 25.0),
	('dessert', 'helado', 'agua', 'Maracuya', 25.0),
	('dessert', 'helado', 'crema', 'Tramontana', 50.0),
	('dessert', 'helado', 'crema', 'Frutos del bosque', 50.0),
	('dessert', 'helado', 'crema', 'Quinotos', 50.0),
	('dinner', 'sandwich', 'lomo', 'Clasico', 450.0),
	('dinner', 'sandwich', 'lomo', 'Completo', 500.0),
	('dinner', 'sandwich', 'lomo', 'Lomo Pizza', 1000.0),
	('dinner', 'carne', 'asado', 'Parrillada', 2000.0),
	('dinner', 'carne', 'asado', 'Choripan', 100.0),
	('dinner', 'sopa', 'crema', 'Sopa de Calabaza', 200.0),
	('dinner', 'sopa', 'crema', 'Sopa de Espinaca', 200.0),
	('dinner', 'sopa', 'caldo', 'Sopa de Verduras', 200.0),
	('dinner', 'verdura', 'papa frita', 'Salchipapa', 1499.99),
	('dinner', 'pasta', 'ramen', 'Miso Ramen', 750.0)
;
