USE ProyectoUM;

INSERT INTO MATERIA (nombre, duracion) VALUES
	('Sistema de Representacion',6),
	('Química General',6),
	('Calculo I',6),
	('Calculo II',6),
	('Calculo III',6),
	('Calculo IV',6),
	('Tecnología Ciencia y Sociedad',6),
	('Física I',6),
	('Física II',6),
	('Algebra y Geometría Analitica',12),
	('Ingles Tecnico',12),
	('Informática I',12),
	('Arquitectura de Computadoras',6),
	('Tecnologia',6),
	('Algebra Lineal',6),
	('Sistemas Operativos',6),
	('Estadística Aplicada I',6),
	('Estadística Aplicada II',6),
	('Computacion',12),
	('Circuitos Electronicos',12),
	('Análisis Numerico',6),
	('Dispositivos Electronicos',6),
	('Higiene y Seguridad Industrial',6),
	('Redes de Datos',6),
	('comunicación de Datos',6),
	('Electrónica Analógica I',6),
	('Programación I',6),
	('Programación II',12),
	('Computación II',12),
	('Circuitos Digitales I',12),
	('Circuitos Digitales II',6),
	('Ingeniería de Software',6),
	('Seguridad Informatica',6),
	('Organizacion',6),
	('Electrónica Analógica II',6),
	('Economía I',6),
	('Sistemas Automáticos y de Control',6),
	('Formulación y Evaluación de Proyectos',6),
	('Ingeniería, Derecho y Ética Profesional',6),
	('Diseño de Base de Datos I',6),
	('Gestión de Calidad y Medio Ambiente',6),
	('Modelos y Simulacion',6),
	('Sistemas Embebidos',6),
	('Inteligencia Artificial',6),
	('Planeamiento y Gestión de Empresas',6),
	('Practica Profesional',12),
	('Trabajo Final',12),
	('Gestión de Recursos Humanos',6),
	('Informática Industrial',6),
	('comunicación de Redes Seguras',6),
	('Habilidades Directivas y Liderazgo',6),
	('Servicios de Aplicacion',6),
	('Gerenciamiento de Proyectos',6),
	('Informática Forense',6),
	('Procesamiento de Imagenes',6),
	('Monitoreo y Gestión de Redes',6),
	('Matemática Discreta y Diseño Logico',6),
	('Análisis de Sistemas I',6),
	('Análisis de Sistemas II',6),
	('Teoría de Compiladores',6),
	('Diseño de Sistemas',6),
	('Teleinformatica',6),
	('Seguridad Informática I',6),
	('Investigación operativa',6),
	('Auditoria de Sistemas I',6),
	('Diseño de Base de Datos II',6),
	('Higiene y Seguridad del Trabajo',6),
	('Seguridad Informática II',6),
	('Servicios de Aplicacion',6),
	('Auditoria de Sistemas II',6),
	('Asesoramiento de Calidad de Software',6),
	('Desarrollo de Sistemas Distribuidos',6),
	('biología I',6),
	('Electrotecnia',6),
	('Biología II',6),
	('Química Biologica',6),
	('Análisis de Circuitos I',6),
	('Análisis de Circuitos II',6),
	('Fisiopatologia',6),
	('Análisis de Señales',6),
	('Fisiología y Biofisica',6),
	('Biomateriales',6),
	('Radiación y Protección Radiologica',6),
	('Instalaciones Hospitalarias',6),
	('Bioinstrumentacion I',6),
	('Electrónica Nuclear',6),
	('Biomecanica',6),
	('Bioinstrumentacion II',6),
	('Equipamiento de Diagnóstico y Terapia',6),
	('Higiene, Seguridad y Saneamiento',6),
	('Ingeniería de Rehabilitacion',6),
	('Medicina Nuclear',6),
	('Evaluación y Seguimiento de Proyectos',6),
	('Sistemas Avanzados de Control',6),
	('Robótica Industrial',6),
	('Evaluación y Gestión Ambiental',6),
	('Órganos Artificiales',6),
	('Química Organica',6),
	('Estabilidad',6),
	('Electrónica Industrial',12),
	('Organización y Administración de Empresas',6),
	('Economía II',6),
	('Materiales y Ensayos',6),
	('Mecánica de los Fluidos',6),
	('Seguridad, Higiene Industrial y Saneamiento',6),
	('Electrónica General y Aplicada',6),
	('Mecánica Aplicada',6),
	('Costos Industriales',6),
	('Termodinámica Industrial',6),
	('Equipamiento Industrial',6),
	('Comercializacion',6),
	('Química Industrial',6),
	('Finanzas de Empresas',6),
	('Administración de Operaciones',6),
	('Informática Industrial',6),
	('Dirección Estrategica',6),
	('Operación y Procesos Industriales',6),
	('Instrumentación Industrial',6),
	('Contaminación Ambiental',6),
	('Geología General',6),
	('Mantenimiento Industrial',6),
	('Perforaciones',6),
	('Tecnología Industrial',6),
	('Idioma Portugues',6),
	('Robótica Industrial',6),
	('Procesos de los Hidrocarburos',6),
	('Instrumentos y Mediciones',6),
	('Maquinas Electricas',12),
	('Mecanismos y Elementos de Maquinas',6),
	('Luminotecnia',6),
	('Electrónica de Potencia',6),
	('Instalaciones Eléctricas I',6),
	('Maquinas Térmicas e Hidraulicas',6),
	('Energías Alternativas I',6),
	('Líneas y Redes Electricas',6),
	('Energías Alternativas II',6),
	('Centrales y Estaciones de Transferencia I',6),
	('Análisis y Operación de Sistemas Eléctricos I',6),
	('Análisis y Operación de Sistemas Eléctricos II',6),
	('Centrales y Estaciones de Transferencia II',6),
	('Instalaciones Eléctricas II',6),
	('Proyecto de Maquinas Electricas',6),
	('Calidad de Potencia',6),
	('Matemática Elemental',6),
	('Logica',6),
	('Sistemas de Información I',6),
	('Ingles I',6),
	('Sistemas de Información II',6),
	('Redes',6),
	('Bases de Datos',6),
	('Programación II',6),
	('Lenguajes de Marcas',6),
	('Entornos de Desarrollo',6),
	('Laboratorio I',6),
	('Ingles II',6),
	('Ingles III',6),
	('Estadística Aplicada',6),
	('Desarrollos Web',6),
	('Gestión de Proyectos',6),
	('Laboratorio II',6),
	('Ética Profesional y Legislación Laboral',6),
	('Aplicaciones Web',6),
	('Diseño de Interfaces Web',6),
	('Aplicaciones Web',6),
	('Física para Videojuegos',6),
	('Argumentos y Guiones',6),
	('Diseño Gráfico',6),
	('Programación de Graficos',6),
	('Desarrollo de Juegos I',6),
	('Desarrollo de Juegos II',6),
	('Generación de Audio',6),
	('Juegos para Internet',6),
	('aplicaciones Moviles',6),
	('Algebra',6),
	('Sonido',6),
	('Termodinamica',6),
	('Estadistica',6),
	('Electronica',6),
	('Acústica I',6),
	('Procesamiento Digital de Señal',6),
	('Control de Ruido',6),
	('Audio',6),
	('Instrumentos y Mediciones Acusticas',6),
	('Acústica II',6),
	('Software para Sonido y Acustica',6),
	('Psicoacustica',6),
	('Refuerzo Sonoro',6),
	('Gestión de Proyectos',6),
	('Laboratorio III',6),
	('Quimica',6),
	('Organización de Empresas',6),
	('Fisica',6),
	('Probabilidad y Estadistica',6),
	('Resistencia de Materiales',6),
	('Mecanica',6),
	('Técnicas de Cultivo',6),
	('Seguridad e Higiene Industrial',6),
	('Legislación Laboral',6),
	('Maquinas Termicas',6),
	('Instalaciones y Maquinas Electricas',6),
	('Automática Industrial',6),
	('Gestión de Mantenimiento Industrial',6),
	('Equipamiento Agroindustrial',6),
	('Instalaciones y Medios de Produccion',6),
	('Gestión de Calidad',6),
	('Practica Profesional Supervisada',6),
	('Sujeto del Aprendizaje I',6),
	('Curriculum I',6),
	('Sistema Educativo',6),
	('Institución Educativa',6),
	('Metodología de la Investigación I',6),
	('Sujeto del Aprendizaje II',6),
	('Curriculum II',6),
	('Mediación Pedagogica',6),
	('Metodología de la Investigación II',6),
	('Curso Complementario de Ingles Tecnico',6),
	('Informática Educativa',6),
	('Innovación y Cambio Institucional',6),
	('Residencia e Investigacion',6),
	('Organización y Gestión Institucional',6),
	('Evaluación de los Aprendizajes',6),
	('Técnicas y Recursos para la Enseñanza',6),
	('Análisis de Software Educativos',6),
	('Propagación y Radiacion',6),
	('Sistemas de Comunicaciones I',6),
	('Sistemas de Control',6),
	('Electrónica de Alta Frecuencia',6),
	('Comunicaciones Digitales',6),
	('Sistemas de Television',6),
	('Matemática Aplicada a la Ingenieria',6),
	('Tecnología de Microondas',6),
	('Comunicación Satelital y Sistemas de Radionavegacion',6),
	('Sistemas de Comunicaciones II',6),
	('Anatomía I',6),
	('Citología e Histología General',6),
	('Embriologia',6),
	('Bioquímica General I',6),
	('Atención al Enfermo I',6),
	('Anatomía II',6),
	('Bioquímica General II',6),
	('Teoría del Hombre',6),
	('Fisiología I',6),
	('Genetica',6),
	('Psicologia',6),
	('Biofisica',6),
	('Inmunologia',6),
	('Bioestadistica',6),
	('Histología Especial',6),
	('Fisiología II',6),
	('Microbiologia',6),
	('Atencion al Enfermo II',6),
	('Fisiopatologia',6),
	('Anatomía Patologica',6),
	('Epidemiologia y Demografia',6),
	('Diagnostico por Imagenes',6),
	('Farmacologia',6),
	('Antropología Medica',6),
	('Geriatria',6),
	('Medicina Nuclear',1),
	('Semiologia',1),
	('Toxicologia',6),
	('Otorrinolaringologia',6),
	('Metodología de la Investgacion',6),
	('Etica',6),
	('Diagnostica',1),
	('Cirugia',6),
	('Urologia',6),
	('Urgencias',6),
	('Economía Sanitaria y Salud Publica',1),
	('Terapeutica',1),
	('Pediatria',3),
	('Ginecologia',3),
	('Enfermedades Infecciosas',3),
	('Traumatologia',3),
	('Obstetricia',3),
	('Medicina Legal y Deontologia',3),
	('Psiquiatria',3),
	('Neurologia',3),
	('Bioetica',3),
	('Atención Medica Primaria',3),
	('Oftalmologia',3),
	('Dermatologia',3),
	('Rehabilitacion',3),
	('Medicina Interna',3),
	('Pediatria',3),
	('Cirugia',3),
	('Gineco-Obstetricia',3),
	('Atención Primaria',3),
	('Atención Primaria Rural',3),
	('Curso Orientación y Desarrollo Profesional',3),
	('Evaluación Sumativa Final Obligatoria',3),
	('Anatomía General y Estomatologica',12),
	('Histología y Embriología General y Dentaria',12),
	('Prevención General y Educación para la Salud',12),
	('Morfología Dentaria',12),
	('Biomateriales',12),
	('Física Biologica',6),
	('Odontología, Ciencia y Sociedad',6),
	('Informática I',6),
	('Anatomía Patológica General y Bucal',12),
	('Fisologia',12),
	('Microbiología y Parasitologia',12),
	('Diagnostico por Imagenes',12),
	('Clínica Preventiva Comunitaria',12),
	('Preclínica de Operatoria Dental',12),
	('Preclínica de Prótesis Completa y Removible',12),
	('Informática II',6),
	('Oclusión I',6),
	('Oclusión II',6),
	('Farmacologia',12),
	('Semiología General',12),
	('Preclínica de Endodoncia',12),
	('Preclínica de Periodoncia',12),
	('Preclínica Prótesis Fija',12),
	('Cirugía y Traumatología Bucomaxilofacial I',12),
	('Cirugía y Traumatología Bucomaxilafacial II',12),
	('Cirugía y Traumatología Bucomaxilafacial III',12),
	('Clínica Operatoria Dental I',12),
	('Clínica de Prótesis Completa',12),
	('Introducción a la Investigación Cientifica',12),
	('Clínica de Endodoncia',12),
	('Clínica Peridoncia',12),
	('Clínica de Operatoria Dental II',12),
	('Clínica de Prótesis Parcial',12),
	('Odontología Sanitaria y Epidemiologia',12),
	('Estomatología I',6),
	('Psicologia',6),
	('Operatoria Dental Conservadora con Mínima Invasion',6),
	('Diagnóstico por Imágenes de Alta Resolución y Alta Complejidad',6),
	('Odontología Integral Adultos',12),
	('Odontología Integral Niños',12),
	('Ortodoncia',12),
	('Integración Hospitalaria',12),
	('Investigación Científica Aplicada',12),
	('Estomatología III',6),
	('Odontología Legal y Ejercicio Profesional',6),
	('Gestión en Salud Publica',6),
	('Bases Biológicas para la Implantologia',6),
	('Anatomia',12),
	('Fisiologia',12),
	('Histologia',12),
	('Física Biologica',12),
	('Psicología Medica',6),
	('Bioquimica',1),
	('Técnicas Kinésicas I',12),
	('Semiopatologia Medico Kinesica',12),
	('Kinefilaxia',12),
	('Ortensis y Protesis',6),
	('Psicomotricidad',12),
	('Técnicas Kinésicas II',12),
	('Semipatologia Quirúrgico Kinesica',12),
	('Kinesiología Medica',12),
	('Fisioterapia',12),
	('Kinefisiatria Estetica',6),
	('Bioinformática y Rehabilitación Computacional',12),
	('Neurologia',1),
	('Kinesiología Quirurgica',12),
	('Kinesiología Legal',6),
	('Deportismo',12),
	('Farmacología Electrofisiokinesica',12),
	('organización Hospitalaria Institucional y Centros de Rehabilitacion',12),
	('Kinefisiatria Ocupacional y Laboral',12),
	('Historia de la Psicologia',6),
	('Biología General y Humana',6),
	('Psicología General',6),
	('Informática Aplicada',6),
	('Perspectivas Antropologicas',6),
	('Corrientes Actuales de Psicologia',6),
	('Neurobiología I',6),
	('Sociología Enfoque en Redes',6),
	('Fundamentos del Pensamiento Científico y Epistemologia',6),
	('Psicología y Problemática Socio-Cultural Actual',6),
	('Psicología Social',6),
	('Neurobiología II',6),
	('Psicología del Desarrollo I',6),
	('Psicología de la Personalidad',6),
	('Problemas Filosóficos en Psicologia',6),
	('Psicoestadistica',6),
	('Psicología del Desarrollo II',6),
	('Ética, Deontología y Legislación Profesional',6),
	('Psicopatología I',6),
	('Perspectivas de Investigación en Psicologia',6),
	('Psicología del Deporte y la Actividad Fisica',6),
	('Consumo Problemático del Alcohol y Otras Drogas',6),
	('problemática Psico-Social de Niños y Adolescentes en Conflicto con la Ley Penal',6),
	('Psicología Humanista y Existencial',6),
	('Métodos de Investigación I',6),
	('Psicología Sistémico Comunicacional',6),
	('Psicología Cognitivo Conductual',6),
	('Métodos de Investigación II',6),
	('Psicopatología II',6),
	('Teoría Psicoanalitica',6),
	('Prevención y Promoción de la Salud en la Tercera Edad',6),
	('Teoría y Procedimientos de Intervención Grupal',6),
	('Gestión Colaborativa de Conflictos',6),
	('Abordaje Psicológico de las Personas con Discapacidad',6),
	('Psicología de las Organizaciones',6),
	('Salud Mental Comunitaria',6),
	('Evaluación y Diagnostico Psicológico I',6),
	('Intervención y Tratamiento Psicológico Psicoanalitico',6),
	('Intervención y Tratamiento Psicológico Cognitivo Conductual',6),
	('Psicología Educacional',6),
	('Orientación y Terapia Familiar',6),
	('Evaluación y Diagnostico Psicológico II',6),
	('Intervención y Tratamiento Psicológico Humanistico-Existencial',6),
	('Intervención y Tratamiento Psicológico Sistemico-Comunicacional',6),
	('Psicofarmacologia',6),
	('Salud Mental Comunitaria',6),
	('Psicología Organizacional',6),
	('Psicología Educacional',6),
	('Abordaje Integral del Paciente Cronico',6),
	('Principios de Intervención Clinica',6),
	('Psicología Jurídico Forense',6),
	('Clínica Psicoanalitica',6),
	('Clínica Humanístico Existencial',6),
	('Clínica Cognitivo Conductual',6),
	('Clínica Sistémico Comunicacional',6),
	('Orientación Jurídico Forense',6),
	('Fundamentos de la Alimentación I',6),
	('Fundamentos de la Alimentación II',6),
	('Nutrición Normal I',6),
	('Saneamiento Ambiental',6),
	('Antropología Social',6),
	('Bromatologia',6),
	('Tecnología Alimentaria',6),
	('Microbiología y Parasitologia',6),
	('Estadística y Bioestadistica',6),
	('Nutrición Normal II',6),
	('Nutrición Materno Infantil',6),
	('Fisiopatología y Dietoterapia del Niño I',6),
	('Fisiopatología y Dietoterapia del Niño II',6),
	('Fisiopatología y Dietoterapia del Adulto I',6),
	('Fisiopatología y Dietoterapia del Adulto II',6),
	('Técnica Dietética y Análisis Sensorial',6),
	('Técnica Dietoterapica',6),
	('Evaluación Nutricional I',6),
	('Economía Familiar',6),
	('Psicologia',6),
	('Evaluación Nutricional II',6),
	('Educación Alimentaria Nutricional',6),
	('Nutrición en Salud Publica',6),
	('Epidemiologia Nutricional',6),
	('Normas de Calidad y Formulación de Alimentos',6),
	('Planificación y Alimentación Industrial',6),
	('Gestión Alimentaria',6),
	('Fisiología del Deporte',6),
	('Metodología de la Investigacion',6),
	('Informática III',6),
	('Comunicación Nutricional',12),
	('Toxicología de los Alimentos',12),
	('Nutrición Deportiva',12),
	('Nutrición en Geriatria',12),
	('Ética y Bioetica',12),
	('Técnicas y Estrategias Profesionales I',6),
	('Organización Sanitaria',6),
	('Entrenamiento Físico Adaptado',6),
	('Desastre I',6),
	('Técnicas y Estrategias Profesionales II',6),
	('Gestión y Organización en Emergencias',6),
	('Supervivencia y Defensa Profesional',6),
	('Desastre II',6),
	('Emergencia Prehospitalarias I',6),
	('Informática – Estadística Aplicada',6),
	('Gestión de Procesos Ante Desastres',6),
	('Emergencias Prehospitalarias II',6),
	('Comunicación en Emergencias',6),
	('Psicología en Emergencias',6),
	('Epidemiologia',6),
	('Emergencias Prehospitalarias III',6),
	('Ética Profesional y Aspectos Legales',6),
	('Instituciones del Derecho Romano',12),
	('Introducción al Derecho',6),
	('Derecho Civil-Parte General',12),
	('Historia de las Instituciones Políticas Argentinas',6),
	('Introducción a la Argumentación Juridica',6),
	('Introducción a la Economia',6),
	('Administracion',6),
	('Contabilidad Basica',6),
	('Introducción a la Retórica Juridica',6),
	('Historia de las Ideas Politicas',6),
	('Derecho Constitucional y Derechos Humanos',6),
	('Derecho de las Obligaciones',6),
	('Derecho de Daños',6),
	('Derecho Comercial y Societario I',6),
	('Derecho Politico',6),
	('Introducción al Derecho Procesal Civil y Comercial',6),
	('Derecho Comercial y Societario II',6),
	('Derecho Penal-Parte General',12),
	('Derecho de los Contratos I',6),
	('Derecho de los Contratos II',6),
	('Derecho Penal-Parte Especial I',6),
	('Derecho Penal-Parte Especial II',6),
	('Finanzas y Régimen Tributario',6),
	('Derecho del Trabajo y Seguridad Social I',6),
	('Derecho del Trabajo y Seguridad Social II',6),
	('Instituciones del Derecho Cambiario y Bancario',6),
	('Transporte y Seguros',6),
	('Métodos Alternativos de Resolución de Conflictos',6),
	('Derecho Procesal Penal I',6),
	('Derecho Procesal Penal II',6),
	('Derecho Reales, Registrables e Intelectuales I',6),
	('Derecho Reales, Registrables e Intelectuales II',6),
	('Derecho Administrativo',6),
	('Derecho Internacional Público y de la Integracion',6),
	('Derecho Procesal Civil y Comercial I',6),
	('Derecho Procesal Civil y Comercial II',6),
	('Concursos y Quiebras',6),
	('Filosofía Juridica',6),
	('Derecho Ambiental y Recursos Naturales I',6),
	('Derecho Ambiental y Recursos Naturales II',6),
	('Derecho de Familia',6),
	('Derecho de Secesiones',6),
	('Derecho Internacional Privado',6),
	('Derecho Romano',6),
	('Introducción al Derecho',6),
	('Títulos de Créditos y otros Papeles de Comercio',6),
	('Derecho Constitucional',6),
	('Derecho Comercial General, Empresario y Societario',6),
	('Contratos Civiles y Comerciales',12),
	('Derecho Procesal Civil',12),
	('Derecho Financiero y Tributario',6),
	('Derecho de Sucesiones',6),
	('Derecho Registral y Practica Registral',6),
	('Derecho Notarial y Practica Notarial',6),
	('Derecho Ambiental y Recursos Naturales',6),
	('Instituciones de Derecho Internacional Privado',6),
	('Derecho Comercial-Parte General',12),
	('Introducción a la Contabilidad',6),
	('Matemáticas I',6),
	('Derecho Público Argentino y de la Integracion',6),
	('Administración I',6),
	('Matemáticas II',6),
	('Contabilidad Basica',6),
	('Estadística para Empresas',6),
	('Derecho Empresario',6),
	('Microeconomia',6),
	('Sistemas y Metodos',6),
	('Administración II',6),
	('Costos Contables y Costos para Decisiones',6),
	('Contratos de la Empresa',6),
	('Portugués I',12),
	('Finanzas Publicas',6),
	('Técnica Impositiva',6),
	('Administración Financiera',6),
	('Control de Gestionad',6),
	('Macroeconomia',6),
	('Contabilidad Superior y Análisis Contable',6),
	('Derechos de Familia y Sucesiones',6),
	('Derecho Concursal',6),
	('Administración III',6),
	('Portugués II',12),
	('Procedimiento Tributario',6),
	('Impuestos',6),
	('Estrategia y Negociacion',6),
	('Auditoria de Estados Contables',6),
	('Mercado de Capitales y Finanzas Empresariales',6),
	('Operatoria de Comercio Exterior',6),
	('Empresas y Negocios Internacionales',6),
	('Contabilidad Publica',6),
	('Auditoria Operativa y de Sistemas Computalizados',6),
	('Actuación Profesional Contable-Juridica',6),
	('Econometria',6),
	('Administración Financiera y Control de Gestion',6),
	('Análisis de Mercado',6),
	('Macroeconomía Comercial, Internacional y Mercosur',6),
	('Toma de Decisiones Económicas en la Empresa',6),
	('Administración de Recursos Humanos',6),
	('Comercializacion',6),
	('Dirección Estrategica',6),
	('Mercado de Capitales y Derivados Financieros',6),
	('Estrategia y Negociacion',6),
	('Impuestos',6),
	('Empresa y Negocios Internacionales',6),
	('Arquitectura I',12),
	('Construcciones I',12),
	('Cultura Aquitectonica',12),
	('Dibujo y expresion',12),
	('Estructuras I',12),
	('Ambiente I',12),
	('Arquitectura II',12),
	('Construcciones II',12),
	('Estructuras II',12),
	('Historia de la Arquitectura y el Urbanismo I',12),
	('Teoria de la Arquitectura y el Urbanismo I',12),
	('Ambiente II',12),
	('Arquitectura III',12),
	('Construcciones III',12),
	('Estructuras III',12),
	('Historia de la Arquitectura y el Urbanismo II',12),
	('Teoría de la Arquitectura y el Urbanismo II',12),
	('Ambiente III',12),
	('Arquitectura IV',12),
	('Construcciones IV',12),
	('Estructuras IV',12),
	('Historia de la Arquitectura y el Urbanismo III',12),
	('Teoría de la Arquitectura y el Urbanismo III',12),
	('Arquitectura V',6),
	('Organización, Administración y Legislacion',6),
	('Proyectos Inmobiliarios',6),
	('Urbanismo',6),
	('Frances',12),
	('Diseño Asistido por Computadora',6),
	('Cultura del diseño I y II',12),
	('Dibujo y Expresión Visual I y II',12),
	('Informática I y II',12),
	('Taller de Introducción al Diseño I y II',12),
	('Diseño Regional',6),
	('Materialización I y II',12),
	('Creatividad en el Diseño',6),
	('Taller de Diseño Integral I y II',12),
	('Psicología de la Percepcion',6),
	('Actuación Profesional',6),
	('Actuación Empresarial',6),
	('Taller Especial de Diseño I y II',12),
	('Introducción a la Investigacion',6),
	('Semiologia',6),
	('Taller de Diseño Estrategico',6),
	('Ergonomia',6),
	('Teoría General del Diseño',6),
	('Metodología del Diseño',6),
	('Marketing Empresario',6),
	('Psicologia',6),
	('Comunicación I',6),
	('Comunicación II',6),
	('Corretaje I',6),
	('Corretaje II',6),
	('Derecho I',6),
	('Derecho II',6),
	('Diseño I',6),
	('Diseño II',6),
	('Inmobiliario I',6),
	('Inmobiliario II',6),
	('Marketing I',6),
	('Marketing II',6),
	('Valuación I',6),
	('Valuación II',6);

SELECT * FROM MATERIA;

INSERT INTO CAR_MAT (ID_materia, ID_carrera) VALUES 
	(1,1),
	(1,2),
	(1,3),
	(1,4),
	(1,5),
	(1,11),
	(1,17),
	(1,18),
	(1,19),
	(1,20),
	(1,21),
	(2,1),
	(2,2),
	(2,3),
	(2,4),
	(2,5),
	(2,9),
	(2,11),
	(2,24),
	(2,25),
	(2,26),
	(2,28),
	(3,1),
	(3,2),
	(3,3),
	(3,4),
	(3,5),
	(3,11),
	(4,1),
	(5,1),
	(6,1),
	(7,1),
	(8,1),
	(9,1),
	(10,1),
	(11,1),
	(12,1),
	(17,1),
	(20,1),
	(21,1),
	(22,1),
	(23,1),
	(26,1),
	(30,1),
	(31,1),
	(34,1),
	(35,1),
	(36,1),
	(37,1),
	(38,1),
	(39,1),
	(45,1),
	(46,1),
	(47,1),
	(48,1),
	(80,1),
	(74,1),
	(95,1),
	(100,1),
	(99,1),
	(105,1),
	(106,1),
	(128,1),
	(142,1),
	(143,1),
	(4,3),
	(7,3),
	(8,3),
	(10,3),
	(11,3),
	(12,3),
	(13,3),
	(15,3),
	(16,3),
	(17,3),
	(18,3),
	(19,3),
	(21,3),
	(23,3),
	(24,3),
	(27,3),
	(28,3),
	(29,3),
	(33,3),
	(34,3),
	(36,3),
	(38,3),
	(39,3),
	(40,3),
	(44,3),
	(45,3),
	(46,3),
	(48,3),
	(47,3),
	(50,3),
	(54,3),
	(58,3),
	(59,3),
	(61,3),
	(63,3),
	(66,3),
	(67,3),
	(470,12),
	(471,12),
	(472,12),
	(473,12),
	(474,12),
	(475,12),
	(476,12),
	(477,12),
	(478,12),
	(479,12),
	(480,12),
	(481,12),
	(482,12),
	(483,12),
	(484,12),
	(485,12),
	(486,12),
	(487,12),
	(488,12),
	(489,12),
	(490,12),
	(491,12),
	(492,12),
	(493,12),
	(494,12),
	(495,12),
	(496,12),
	(497,12),
	(498,12),
	(499,12),
	(500,12),
	(501,12),
	(502,12),
	(503,12),
	(504,12),
	(505,12),
	(506,12),
	(507,12),
	(509,12),
	(510,12),
	(511,12),
	(512,12),
	(513,12),
	(514,12),
	(515,12),
	(516,13),
	(517,13),
	(518,13),
	(519,13),
	(520,13),
	(521,13),
	(522,13),
	(523,13),
	(524,13),
	(525,13),
	(526,13),
	(527,13),
	(528,15),
	(529,15),
	(530,15),
	(531,15),
	(532,15),
	(533,15),
	(534,15),
	(535,15),
	(536,15),
	(537,15),
	(538,15),
	(539,15),
	(540,15),
	(541,15),
	(542,15),
	(543,15),
	(544,15),
	(545,15),
	(546,15),
	(547,15),
	(548,15),
	(549,15),
	(550,15),
	(551,15),
	(552,15),
	(553,15),
	(554,15),
	(555,15),
	(556,15),
	(557,15),
	(559,15),
	(558,15),
	(562,16),
	(563,16),
	(564,16),
	(565,16),
	(566,16),
	(567,16),
	(568,16),
	(574,17),
	(575,17),
	(576,17),
	(577,17),
	(578,17),
	(579,17),
	(581,17),
	(582,17),
	(583,17),
	(584,17),
	(585,17),
	(586,17),
	(587,17),
	(588,17),
	(589,17),
	(590,17),
	(591,17),
	(592,17),
	(593,17),
	(594,17),
	(595,17),
	(596,17),
	(597,17),
	(598,17),
	(599,17),
	(600,17),
	(419,28),
	(420,28),
	(421,28),
	(422,28),
	(423,28),
	(424,28),
	(425,28),
	(426,28),
	(427,28),
	(428,28),
	(429,28),
	(430,28),
	(431,28),
	(432,28),
	(433,28),
	(434,28),
	(435,28),
	(436,28),
	(437,28),
	(438,28),
	(439,28),
	(440,28),
	(441,28),
	(442,28),
	(443,28),
	(444,28),
	(445,28),
	(446,28),
	(447,28),
	(448,28),
	(449,28),
	(450,28),
	(451,28),
	(452,28),
	(453,28),
	(454,28),
	(234,24),
	(235,24),
	(236,24),
	(237,24),
	(238,24),
	(239,24),
	(240,24),
	(245,24),
	(246,24),
	(247,24),
	(248,24),
	(249,24),
	(241,24),
	(242,24),
	(243,24),
	(244,24),
	(250,24),
	(251,24),
	(252,24),
	(253,24),
	(254,24),
	(255,24),
	(256,24),
	(257,24),
	(258,24),
	(259,24),
	(260,24),
	(261,24),
	(262,24),
	(263,24),
	(264,24),
	(265,24),
	(266,24),
	(267,24),
	(268,24),
	(269,24),
	(270,24),
	(271,24),
	(272,24),
	(273,24),
	(274,24),
	(275,24),
	(276,24),
	(277,24),
	(278,24),
	(279,24),
	(280,24),
	(281,24),
	(282,24),
	(283,24),
	(284,24),
	(285,24),
	(286,24),
	(363,27),
	(364,27),
	(365,27),
	(366,27),
	(367,27),
	(368,27),
	(369,27),
	(370,27),
	(371,27),
	(372,27),
	(373,27),
	(374,27),
	(375,27),
	(376,27),
	(377,27),
	(378,27),
	(379,27),
	(380,27),
	(381,27),
	(382,27),
	(383,27),
	(384,27),
	(385,27),
	(386,27),
	(387,27),
	(388,27),
	(389,27),
	(390,27),
	(391,27),
	(392,27),
	(393,27),
	(394,27),
	(395,27),
	(396,27),
	(397,27),
	(398,27),
	(399,27),
	(400,27),
	(401,27),
	(402,27),
	(403,27),
	(404,27),
	(405,27),
	(406,27),
	(407,27),
	(408,27),
	(409,27),
	(410,27),
	(411,27),
	(412,27),
	(413,27),
	(414,27),
	(415,27),
	(416,27),
	(417,27),
	(623,22),
	(624,22),
	(625,22),
	(626,22),
	(627,22),
	(628,22),
	(629,22),
	(630,22),
	(631,22),
	(632,22),
	(633,22),
	(634,22),
	(635,22),
	(636,22);

SELECT MATERIA.nombre FROM MATERIA,CAR_MAT, CARRERA WHERE CARRERA.ID_carrera = CAR_MAT.ID_carrera AND CAR_MAT.ID_carrera = 1 AND MATERIA.ID_materia=CAR_MAT.ID_materia; 